@startuml
left to right direction

actor "Secretária" as Secretaria

rectangle Sistema {
    usecase "Visualizar Tabela de\nMensalidades dos Alunos" as UC09
    usecase "Atualizar Pagamento" as UC10
    usecase "Gerar Comprovante" as UC11
    usecase "Exportar como PDF" as UC11a
    usecase "Exportar como Word" as UC11b
    usecase "Exportar Dados Financeiros\nComo Planilha" as UC12
}

Secretaria --> UC09
Secretaria --> UC10
Secretaria --> UC11
Secretaria --> UC12

UC11 <.. UC11a : <<extend>>
UC11 <.. UC11b : <<extend>>

@enduml
