@startuml
left to right direction

actor "Administrador" as Administrador

usecase "Cadastrar Usuário" as UC01
usecase "Cadastrar Ponto de Embarque" as UC13

Administrador --> UC01
Administrador --> UC13

@enduml
