@startuml
start
:Acessar controle de rota;
:Consultar próximo ponto;
if (Ponto atual definido?) then (sim)
  if (Existe próximo ponto?) then (sim)
    :Exibir ponto atual;
    :Exibir próximo ponto;
  else (não)
    :Informar último ponto da rota;
  endif
else (não)
  :Solicitar definição do ponto atual;
endif
stop
@enduml
