@startuml
skinparam state {
  BackgroundColor White
  BorderColor Black
}

state "NAO_INICIADA" as NaoIniciada
state "EM_ANDAMENTO" as EmAndamento
state "FINALIZADA" as Finalizada

[*] --> NaoIniciada

NaoIniciada : entry / carregarRota(data)

NaoIniciada --> EmAndamento : iniciar() [status == NAO_INICIADA] / notificarAlunos()
note on link
  <b>Evento:</b> Motorista clica em 'Iniciar Viagem'
  <b>Guarda:</b> Rota não pode ter sido iniciada
  <b>Ação:</b> Atualiza status e notifica (Observer)
end note

EmAndamento : entry / registrarHoraInicio()
EmAndamento : do / monitorarTrajeto()

EmAndamento --> Finalizada : finalizar() 
note on link
  <b>Evento:</b> Motorista clica em 'Finalizar Rota'
  <b>Ação:</b> Encerra a atividade monitorarTrajeto()
end note

Finalizada : entry / registrarHoraFim()

Finalizada --> [*]
@enduml