@startuml
left to right direction

actor Aluno

usecase "Responder Enquete" as UC3
usecase "Selecionar Data" as UC3a
usecase "Informar Trajeto" as UC3b

UC3 ..> UC3a : <<include>>
UC3 ..> UC3b : <<include>>

Aluno --> UC3

@enduml
