@startuml
left to right direction

actor Secretaria as "Secretária"

usecase "Visualizar Tabela Financeira" as UC7
usecase "Consultar Pagamentos Realizados" as UC7a
usecase "Consultar Pagamentos Pendentes" as UC7b

UC7 ..> UC7a : <<include>>
UC7 ..> UC7b : <<include>>

Secretaria --> UC7

@enduml
